### ISSUE TITLE
Feature request: Option to disable notifications

### ISSUE THREAD

**Issue by nick42d** [savely-krasovsky/waybar-updates#26]
I currently get notifications from eos-update-notifier, so using waybar-updates gives me duplicate notifications. It would be handy to have an option to disable these.

**Comment by juanscr** [comment]
Hi, just in case I forked the project and created a pull request for solving this. You can clone mine and use it instead or vote for merging the PR.

**Comment by savely-krasovsky** [comment]
Merged and released as part of v0.4.0!
