### ISSUE TITLE
Icons no longer showing in the waybar

### ISSUE THREAD

**Issue by Licensed-Idiot** [savely-krasovsky/waybar-updates#31]
The waybar-updates module no longer shows up in waybar, not sure why this is happening all of a sudden, here's what the config looks like,

`  "modules-left": ["sway/workspaces", "custom/updates", "tray", "sway/mode"],`

```
  "custom/updates": {
    "format": "{icon}{}",
    "return-type": "json",
    "format-icons": {
      "pending-updates": "󰮯 ",
      "updated": ""
    },
    "exec-if": "which waybar-updates",
    "exec": "waybar-updates"
},
```

```
@keyframes blink {
  to {
    color: #ebdbb2;
  }

#custom-updates {
	animation-timing-function: linear;
	animation-iteration-count: infinite;
	animation-direction: alternate;
}
#custom-updates.pending-updates {
	animation-name: blink;
	animation-duration: 3s;
}
```

**Comment by Saligz** [comment]
same here
[2024-09-13 12:17:56.792] [error] custom/pacman: cannot switch from manual to automatic argument indexing

**Comment by savely-krasovsky** [comment]
To be clear: I didn't release any new update.

**Comment by vocatart** [comment]
> same here [2024-09-13 12:17:56.792] [error] custom/pacman: cannot switch from manual to automatic argument indexing

having the same issue

**Comment by savely-krasovsky** [comment]
It's regression in waybar: https://github.com/Alexays/Waybar/issues/3597

**Comment by savely-krasovsky** [comment]
It was kinda fixed, but it seems the problem persist, so I am linking the new issue: https://github.com/Alexays/Waybar/issues/3607

**Comment by prfiredragon** [comment]
I don't know why. I have the same problem with updates and media player. I change the order like that

"format": "{} {icon}",
and the icons and Text show up again.

**Comment by prfiredragon** [comment]
If i switch it back the problem returns. For the test I only switch the media player.


![20240915_14h37m26s_grim](https://github.com/user-attachments/assets/c4a3b21b-91fa-4e6b-99ed-b7538dc3c93e)

**Comment by vocatart** [comment]
> I don't know why. I have the same problem with updates and media player. I change the order like that
> 
> "format": "{} {icon}", and the icons and Text show up again.
> 
> ![20240915_14h35m42s_grim](https://private-user-images.githubusercontent.com/18429660/367615497-79a37cd0-1a57-4f47-8c45-e33554369d7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjU2ODMsIm5iZiI6MTcyNjQyNTM4MywicGF0aCI6Ii8xODQyOTY2MC8zNjc2MTU0OTctNzlhMzdjZDAtMWE1Ny00ZjQ3LThjNDUtZTMzNTU0MzY5ZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE4MzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjAyNWZiZDk5NTU3ODhkYjNlYjg3YWI1Yzk3ZjE3NmU5NjFiYzI0NWZiZDBhNjEyNzRhZGRmZWE0ZWFkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q3t00jIUr_zoGvA3m-bNAzveQIuVYk_OYmXKvgXAAZE)
> 
> ![20240915_14h34m52s_grim](https://private-user-images.githubusercontent.com/18429660/367615454-442c4235-8e6b-4b1b-894b-4546ecba1620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjU2ODMsIm5iZiI6MTcyNjQyNTM4MywicGF0aCI6Ii8xODQyOTY2MC8zNjc2MTU0NTQtNDQyYzQyMzUtOGU2Yi00YjFiLTg5NGItNDU0NmVjYmExNjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE4MzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZGZhOGI4ZDA3OWM1NTIzZDMwNzJlNzczZWRkZTZmMGQzN2M5MjFmYjI2OTdjZGM1OWNlOTZiZGU1ZjBiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RFA08P89C-TW7Ea1g6mrF9FCHT9D22IljrU8cWoYuWc) ![20240915_14h34m59s_grim](https://private-user-images.githubusercontent.com/18429660/367615461-472d757c-a47e-4504-826e-a2bb8e1e5076.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjU2ODMsIm5iZiI6MTcyNjQyNTM4MywicGF0aCI6Ii8xODQyOTY2MC8zNjc2MTU0NjEtNDcyZDc1N2MtYTQ3ZS00NTA0LTgyNmUtYTJiYjhlMWU1MDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE4MzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzdhNDNkMzU2ZjNmOTI1N2IxNzJmMjViNjIyZmI3NTU2YmQ0ZWY0MTEzM2Y4NzkyYzc0YTNhYjUyNWY3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n2Bj8F8ilGMXwSCNDNR8ap4yBB59KJ5OhThW8wxoC7Q)

just tried swapping the arguments as well and seems to have fixed it. weird.

**Comment by savely-krasovsky** [comment]
Please update to the latest `0.11.0-3` (and optionally restore order), it should work as previously.

**Comment by techware01** [comment]
Hey, 
thx for this thread.
I have waybar version `0.11.0-3` installed, but the issue still consists. Swapping icon and text however does the trick.

**Comment by JettScythe** [comment]
instead of    
` "format": "{icon}{}",`
 use
`"format": "{icon}{text}",`
